### ISSUE TITLE
'protes' error when running clac.py

### ISSUE THREAD

**Issue by Schortenger** [anabatsh/TT_pro#1]
Hi, I'm trying to run the `calc.py` file in the folder of result_paper, but I found that the `protes` used in this file is not the traditional `protes`. Can you share me about this file?

**Comment by AndreiChertkov** [comment]
Dear Mr. Schortenger, thank you for your interest in the PROTES method. This repository contains deprecated code, as noted in the README file. The results from the "result_paper" folder were re-obtained by us using the updated and improved code of the PROTES method. We invite you to check them out in the new repository (https://github.com/anabatsh/PROTES) in the "calc" folder (please also see the comments in the README file). In the coming days, we will very significantly update the arXiv text of the paper, including new results and a link to the new repository.
